name: Easy Test

on:
  workflow_dispatch:
    inputs:
      windows:
        description: 'Run tests on Windows'
        required: false
        default: true
        type: boolean

jobs:
  test-windows:
    runs-on: windows-latest
    if: github.event.inputs.windows == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache Chocolatey packages
      uses: actions/cache@v4
      with:
        path: C:\ProgramData\chocolatey\lib
        key: ${{ runner.os }}-choco-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-choco-

    - name: Install Chocolatey packages
      run: choco install cmake

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON -DBUILD_BENCHMARKS=ON
        cmake --build . --config Release --parallel

    - name: Run tests
      run: |
        cd build
        ctest -C Release --output-on-failure
      shell: bash